version: "3.0"
services:
  # postgres:
  #   image: "postgres"
  #   ports:
  #     - "5432:5432"
  redis:
    image: "redis"
    hostname: redis
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8000:8081"
  auth:
    image: "s-auth:1.0.1"
    ports:
      - "8084:8084"
    env_file:
      - ./.env.local
    depends_on:
      - redis
      - eureka
  places:
    image: "s-places:1.0.0"
    ports:
      - "8085:8081"
    env_file:
      - ./.env.local
    depends_on:
      - redis
      - eureka
  pr:
    image: "s-pr:1.0.3"
    ports:
      - "8086:8080"
    env_file:
      - ./.env.local
    depends_on:
      - redis
      - eureka
  eureka:
    image: "s-service-discovery:1.0.0"
    ports:
      - "8761:8761"
