version: "3.0"
services:
  # postgres:
  #   image: "postgres"
  #   ports:
  #     - "5432:5432"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  auth:
    image: "s-auth:1.0.0"
    ports:
      - "8084:8084"
    env_file:
      - ./.env.local
    depends_on:
      - redis
      - eureka
  places:
    image: "s-places:1.0.0"
    ports:
      - "8081:8081"
    env_file:
      - ./.env.local
    depends_on:
      - redis
      - eureka
  eureka:
    image: "s-service-discovery:1.0.0"
    ports:
      - "8761:8761"
