kafka:
  host: ${KAFKA_HOST:172.17.0.1}
  port: ${KAFKA_PORT:9092}
  topics:
    pr-purchase: ${TOPICS_PR_PURCHASE:pr-purchase}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:nothost}:${KAFKA_PORT:9092}