server:
  port: ${AUTH_PORT:8082}
  servlet:
    context-path: /api/v1/auth

spring:
  application:
    name: Auth
  jpa:
    open-in-view: false
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://172.17.0.1:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:pass}

secrets:
  jwt:
    key: ${JWT_SECRET:hello_world}