spring:
  profiles:
    include:
      - database
server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api/places/v1

jwt:
  secret-key: ${JWT_SECRET:Q8Di7/+nCH/V8fQyB7jDZAxQLAos/pmEZw/K1KecaQQ=}